# Generated by Django 5.1.10 on 2025-09-25 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeadWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Pronunciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pronunce', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField(help_text='the order of priority')),
                ('headword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.headword')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
