# Generated by Django 5.1.10 on 2025-09-25 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='the order of priority')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.category')),
                ('headword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.headword')),
            ],
        ),
        migrations.AddField(
            model_name='headword',
            name='category',
            field=models.ManyToManyField(blank=True, through='test_app.CategoryMapping', to='test_app.category'),
        ),
        migrations.AddConstraint(
            model_name='categorymapping',
            constraint=models.UniqueConstraint(fields=('headword', 'category'), name='unique_headword_category'),
        ),
    ]
